import type { RoomSetObjectType } from "@/lib/room-set/spatial-types";

import type { PlannerTldrawKind } from "./planner-shape-types";

export const ROOM_SET_COMPONENT_CATEGORY_IDS = [
  "tables",
  "seating",
  "stages",
  "av",
  "registration",
  "fnb",
  "lounge",
  "booths",
  "decor",
  "service",
  "safety",
  "walls",
] as const;

export type RoomSetComponentCategoryId = (typeof ROOM_SET_COMPONENT_CATEGORY_IDS)[number];

export type RoomSetComponentVisualVariant =
  | "round"
  | "rect"
  | "row"
  | "zone"
  | "wall"
  | "door"
  | "kiosk"
  | "cocktailCluster"
  | "chair";

export type RoomSetSetupComplexity = "low" | "medium" | "high";

export type RoomSetSmartMetadata = Readonly<{
  clearanceRequirements: readonly string[];
  capacityLogic: string;
  staffingImpact: string;
  setupComplexity: RoomSetSetupComplexity;
  setupEffort: string;
  strikeEffort: string;
  operationalDependencies: readonly string[];
  serviceAccessRequirements: readonly string[];
  adaEgressImplications: readonly string[];
  avSightlineImplications: readonly string[];
  fnbQueueServiceImplications: readonly string[];
  operationalWarnings: readonly string[];
}>;

export type RoomSetComponentBaseDefinition = Readonly<{
  id: string;
  label: string;
  category: RoomSetComponentCategoryId;
  shapeType: PlannerTldrawKind;
  domainKind: RoomSetObjectType;
  widthLu: number;
  depthLu: number;
  spacingServiceLu: number;
  spacingAisleLu: number;
  capacitySeated: number;
  capacityStaff: number;
  neutralNote: string;
  defaultRotationDeg?: number;
  visualVariant: RoomSetComponentVisualVariant;
  iconKey: string;
  description: string;
  tags: readonly string[];
}>;

export type RoomSetComponentDefinition = RoomSetComponentBaseDefinition &
  Readonly<{
    smart: RoomSetSmartMetadata;
  }>;

export const ROOM_SET_COMPONENT_CATEGORIES: ReadonlyArray<
  Readonly<{
    id: RoomSetComponentCategoryId;
    title: string;
    description: string;
    tone: string;
    iconKey: string;
  }>
> = [
  { id: "tables", title: "Tables", description: "Dining, banquet, and standing surfaces", tone: "sky", iconKey: "circle" },
  { id: "seating", title: "Seating", description: "Guest seating rows and individual seats", tone: "blue", iconKey: "armchair" },
  { id: "stages", title: "Stages", description: "Performance decks and riser footprints", tone: "amber", iconKey: "theater" },
  { id: "av", title: "AV", description: "Screens, control, and production positions", tone: "violet", iconKey: "monitor" },
  { id: "registration", title: "Registration", description: "Check-in, kiosks, and queue control", tone: "lime", iconKey: "clipboard" },
  { id: "fnb", title: "F&B", description: "Service lines, bars, and beverage stations", tone: "orange", iconKey: "utensils" },
  { id: "lounge", title: "Lounge", description: "Soft seating and low-density hospitality", tone: "rose", iconKey: "sofa" },
  { id: "booths", title: "Booths", description: "Sponsor and exhibit footprints", tone: "cyan", iconKey: "booth" },
  { id: "decor", title: "Decor", description: "Scenic, plants, and low-risk decor cues", tone: "emerald", iconKey: "sparkles" },
  { id: "service", title: "Service", description: "Back-of-house access and storage zones", tone: "slate", iconKey: "route" },
  { id: "safety", title: "Safety / Egress", description: "Clearance paths and accessibility zones", tone: "red", iconKey: "shield" },
  { id: "walls", title: "Walls / Dividers", description: "Pipe, drape, airwalls, and separators", tone: "zinc", iconKey: "wall" },
];

const ROOM_SET_COMPONENT_BASES = [
  {
    id: "table-round-60",
    label: "60in round",
    category: "tables",
    shapeType: "planner-banquet-round",
    domainKind: "banquet_table",
    widthLu: 6.1,
    depthLu: 6.1,
    spacingServiceLu: 2,
    spacingAisleLu: 4,
    capacitySeated: 8,
    capacityStaff: 0,
    neutralNote: "",
    visualVariant: "round",
    iconKey: "circle",
    description: "Standard 60 inch dining round with chair/service clearance metadata.",
    tags: ["round", "banquet", "dinner", "table", "60"],
  },
  {
    id: "table-round-72",
    label: "72in round",
    category: "tables",
    shapeType: "planner-banquet-round",
    domainKind: "banquet_table",
    widthLu: 7.3,
    depthLu: 7.3,
    spacingServiceLu: 2.5,
    spacingAisleLu: 4.5,
    capacitySeated: 10,
    capacityStaff: 0,
    neutralNote: "",
    visualVariant: "round",
    iconKey: "circle",
    description: "Larger banquet round for 10-seat dinner layouts.",
    tags: ["round", "banquet", "dinner", "table", "72"],
  },
  {
    id: "table-banquet-6ft",
    label: "6ft banquet",
    category: "tables",
    shapeType: "planner-classroom-table",
    domainKind: "classroom_table",
    widthLu: 7.3,
    depthLu: 2.4,
    spacingServiceLu: 1.5,
    spacingAisleLu: 3,
    capacitySeated: 6,
    capacityStaff: 0,
    neutralNote: "",
    visualVariant: "rect",
    iconKey: "table",
    description: "Two-sided six foot rectangular banquet table with three seats per long side.",
    tags: ["banquet", "rectangular", "six foot", "classroom", "two sided"],
  },
  {
    id: "table-cocktail",
    label: "Cocktail table",
    category: "tables",
    shapeType: "planner-banquet-round",
    domainKind: "banquet_table",
    widthLu: 3.7,
    depthLu: 3.7,
    spacingServiceLu: 2,
    spacingAisleLu: 3,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Standing hospitality touchpoint",
    visualVariant: "round",
    iconKey: "circle",
    description: "Highboy/cocktail table for receptions and networking.",
    tags: ["cocktail", "highboy", "reception", "standing"],
  },
  {
    id: "table-cocktail-cluster",
    label: "Cocktail cluster",
    category: "tables",
    shapeType: "planner-banquet-round",
    domainKind: "banquet_table",
    widthLu: 6.2,
    depthLu: 6.2,
    spacingServiceLu: 2,
    spacingAisleLu: 3,
    capacitySeated: 4,
    capacityStaff: 0,
    neutralNote: "Highboy with four stools rendered as one operational cluster",
    visualVariant: "cocktailCluster",
    iconKey: "circle",
    description: "Reception highboy cluster with stools, optimized as one canvas object.",
    tags: ["cocktail", "highboy", "reception", "standing", "cluster", "stools"],
  },
  {
    id: "seating-theater-row",
    label: "14-chair row",
    category: "seating",
    shapeType: "planner-theater-row",
    domainKind: "chair_block",
    widthLu: 44,
    depthLu: 5.5,
    spacingServiceLu: 1,
    spacingAisleLu: 4,
    capacitySeated: 14,
    capacityStaff: 0,
    neutralNote: "",
    visualVariant: "row",
    iconKey: "row",
    description: "Straight theater seating row with fourteen indexed chairs.",
    tags: ["theater", "chairs", "audience", "row", "fourteen", "14"],
  },
  {
    id: "seating-chair-single",
    label: "Single chair",
    category: "seating",
    shapeType: "planner-theater-row",
    domainKind: "chair_block",
    widthLu: 2.4,
    depthLu: 2.8,
    spacingServiceLu: 0.8,
    spacingAisleLu: 2,
    capacitySeated: 1,
    capacityStaff: 0,
    neutralNote: "Single assignment-ready chair",
    visualVariant: "chair",
    iconKey: "armchair",
    description: "Manual single chair with one stable seat target.",
    tags: ["chair", "single", "seat", "manual"],
  },
  {
    id: "seating-chair-row-5",
    label: "5-chair row",
    category: "seating",
    shapeType: "planner-theater-row",
    domainKind: "chair_block",
    widthLu: 16,
    depthLu: 4,
    spacingServiceLu: 1,
    spacingAisleLu: 3,
    capacitySeated: 5,
    capacityStaff: 0,
    neutralNote: "Manual five-chair row",
    visualVariant: "row",
    iconKey: "row",
    description: "Manual row of five indexed chairs.",
    tags: ["chair", "chairs", "row", "five", "5", "manual"],
  },
  {
    id: "seating-chair-row-10",
    label: "10-chair row",
    category: "seating",
    shapeType: "planner-theater-row",
    domainKind: "chair_block",
    widthLu: 30,
    depthLu: 4.5,
    spacingServiceLu: 1,
    spacingAisleLu: 4,
    capacitySeated: 10,
    capacityStaff: 0,
    neutralNote: "Manual ten-chair row",
    visualVariant: "row",
    iconKey: "row",
    description: "Manual row of ten indexed chairs.",
    tags: ["chair", "chairs", "row", "ten", "10", "manual"],
  },
  {
    id: "seating-chair-block-20",
    label: "20-chair block",
    category: "seating",
    shapeType: "planner-theater-row",
    domainKind: "chair_block",
    widthLu: 30,
    depthLu: 10,
    spacingServiceLu: 1,
    spacingAisleLu: 4,
    capacitySeated: 20,
    capacityStaff: 0,
    neutralNote: "Manual twenty-chair block",
    visualVariant: "row",
    iconKey: "row",
    description: "Manual chair block with twenty indexed seats.",
    tags: ["chair", "chairs", "block", "section", "twenty", "20", "manual"],
  },
  {
    id: "seating-chair-block-custom",
    label: "Custom chair block",
    category: "seating",
    shapeType: "planner-theater-row",
    domainKind: "chair_block",
    widthLu: 24,
    depthLu: 8,
    spacingServiceLu: 1,
    spacingAisleLu: 4,
    capacitySeated: 12,
    capacityStaff: 0,
    neutralNote: "Manual custom chair block",
    visualVariant: "row",
    iconKey: "row",
    description: "Manual chair block starter with indexed seats.",
    tags: ["chair", "chairs", "block", "section", "custom", "manual"],
  },
  {
    id: "seating-classroom-row",
    label: "Classroom row",
    category: "seating",
    shapeType: "planner-classroom-table",
    domainKind: "classroom_table",
    widthLu: 32,
    depthLu: 8,
    spacingServiceLu: 1.5,
    spacingAisleLu: 4,
    capacitySeated: 12,
    capacityStaff: 0,
    neutralNote: "",
    visualVariant: "row",
    iconKey: "row",
    description: "Training row with tables and paired seating.",
    tags: ["classroom", "training", "desks", "row"],
  },
  {
    id: "seating-stool",
    label: "Stool",
    category: "seating",
    shapeType: "planner-operational-fixture",
    domainKind: "chair_block",
    widthLu: 2,
    depthLu: 2,
    spacingServiceLu: 1,
    spacingAisleLu: 2,
    capacitySeated: 1,
    capacityStaff: 0,
    neutralNote: "",
    visualVariant: "chair",
    iconKey: "stool",
    description: "Single stool or bar-height seat.",
    tags: ["stool", "chair", "bar", "seat"],
  },
  {
    id: "seating-lounge-chair",
    label: "Lounge chair",
    category: "lounge",
    shapeType: "planner-operational-fixture",
    domainKind: "chair_block",
    widthLu: 3.6,
    depthLu: 3.6,
    spacingServiceLu: 1.5,
    spacingAisleLu: 3,
    capacitySeated: 1,
    capacityStaff: 0,
    neutralNote: "",
    visualVariant: "chair",
    iconKey: "armchair",
    description: "Soft seat for lounge groupings.",
    tags: ["lounge", "chair", "soft seating"],
  },
  {
    id: "stage-small",
    label: "Small stage",
    category: "stages",
    shapeType: "planner-stage",
    domainKind: "stage",
    widthLu: 24,
    depthLu: 12,
    spacingServiceLu: 2,
    spacingAisleLu: 6,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Presentation platform",
    visualVariant: "rect",
    iconKey: "theater",
    description: "Compact stage for remarks, fireside chats, or awards moments.",
    tags: ["stage", "small", "presentation"],
  },
  {
    id: "stage-keynote",
    label: "Keynote stage",
    category: "stages",
    shapeType: "planner-stage",
    domainKind: "stage",
    widthLu: 48,
    depthLu: 20,
    spacingServiceLu: 3,
    spacingAisleLu: 8,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Main-stage production footprint",
    visualVariant: "rect",
    iconKey: "theater",
    description: "Main keynote stage with backstage and downstage clearance metadata.",
    tags: ["stage", "keynote", "main", "production"],
  },
  {
    id: "stage-riser",
    label: "Riser",
    category: "stages",
    shapeType: "planner-stage",
    domainKind: "stage",
    widthLu: 12,
    depthLu: 8,
    spacingServiceLu: 2,
    spacingAisleLu: 4,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Small raised platform",
    visualVariant: "rect",
    iconKey: "riser",
    description: "Low riser for panels, camera platforms, or announcements.",
    tags: ["riser", "platform", "camera", "panel"],
  },
  {
    id: "av-confidence-monitor",
    label: "Confidence monitor",
    category: "av",
    shapeType: "planner-screen-led",
    domainKind: "screen",
    widthLu: 6,
    depthLu: 2,
    spacingServiceLu: 1,
    spacingAisleLu: 2,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Presenter-facing display",
    visualVariant: "rect",
    iconKey: "monitor",
    description: "Downstage confidence monitor footprint.",
    tags: ["av", "monitor", "confidence", "stage"],
  },
  {
    id: "av-projector-screen",
    label: "Projector screen",
    category: "av",
    shapeType: "planner-screen-led",
    domainKind: "screen",
    widthLu: 20,
    depthLu: 2,
    spacingServiceLu: 1,
    spacingAisleLu: 4,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Projection plane",
    visualVariant: "rect",
    iconKey: "monitor",
    description: "Projection screen with front-of-room throw awareness metadata.",
    tags: ["av", "screen", "projector", "projection"],
  },
  {
    id: "av-led-wall",
    label: "LED wall",
    category: "av",
    shapeType: "planner-screen-led",
    domainKind: "screen",
    widthLu: 32,
    depthLu: 3,
    spacingServiceLu: 1.5,
    spacingAisleLu: 5,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "LED video wall",
    visualVariant: "rect",
    iconKey: "monitor",
    description: "Wide LED wall / scenic video surface.",
    tags: ["av", "led", "wall", "screen"],
  },
  {
    id: "av-speaker-stack",
    label: "Speaker stack",
    category: "av",
    shapeType: "planner-operational-fixture",
    domainKind: "av_table",
    widthLu: 3,
    depthLu: 3,
    spacingServiceLu: 1.5,
    spacingAisleLu: 3,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Audio stack",
    visualVariant: "rect",
    iconKey: "speaker",
    description: "Speaker/sub stack with service clearance.",
    tags: ["av", "audio", "speaker", "pa"],
  },
  {
    id: "av-foh-control",
    label: "FOH control",
    category: "av",
    shapeType: "planner-av-table",
    domainKind: "av_table",
    widthLu: 10,
    depthLu: 6,
    spacingServiceLu: 2,
    spacingAisleLu: 4,
    capacitySeated: 0,
    capacityStaff: 2,
    neutralNote: "",
    visualVariant: "rect",
    iconKey: "sliders",
    description: "Front-of-house control table for audio, show call, or playback.",
    tags: ["av", "foh", "control", "tech"],
  },
  {
    id: "registration-desk",
    label: "Registration desk",
    category: "registration",
    shapeType: "planner-registration-desk",
    domainKind: "registration_desk",
    widthLu: 12,
    depthLu: 3,
    spacingServiceLu: 2,
    spacingAisleLu: 6,
    capacitySeated: 0,
    capacityStaff: 3,
    neutralNote: "",
    visualVariant: "rect",
    iconKey: "clipboard",
    description: "Staffed registration desk with guest-side queue clearance.",
    tags: ["registration", "check-in", "desk"],
  },
  {
    id: "registration-kiosk",
    label: "Self-check-in kiosk",
    category: "registration",
    shapeType: "planner-operational-fixture",
    domainKind: "registration_desk",
    widthLu: 2.5,
    depthLu: 2.5,
    spacingServiceLu: 1,
    spacingAisleLu: 4,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Self-service check-in",
    visualVariant: "kiosk",
    iconKey: "kiosk",
    description: "Self-check-in station or badge-printing kiosk.",
    tags: ["registration", "kiosk", "check-in", "self service"],
  },
  {
    id: "registration-queue-lane",
    label: "Queue lane",
    category: "registration",
    shapeType: "planner-aisle-zone",
    domainKind: "aisle_zone",
    widthLu: 6,
    depthLu: 32,
    spacingServiceLu: 0,
    spacingAisleLu: 0,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Managed queue path",
    visualVariant: "zone",
    iconKey: "route",
    description: "Stanchion or managed guest queue lane.",
    tags: ["registration", "queue", "line", "stanchion"],
  },
  {
    id: "fnb-buffet-line",
    label: "Buffet line",
    category: "fnb",
    shapeType: "planner-buffet",
    domainKind: "buffet",
    widthLu: 18,
    depthLu: 4,
    spacingServiceLu: 3,
    spacingAisleLu: 8,
    capacitySeated: 0,
    capacityStaff: 4,
    neutralNote: "",
    visualVariant: "rect",
    iconKey: "utensils",
    description: "Buffet/service line with guest-side queuing clearance.",
    tags: ["food", "beverage", "buffet", "service"],
  },
  {
    id: "fnb-portable-bar",
    label: "Portable bar",
    category: "fnb",
    shapeType: "planner-bar",
    domainKind: "bar",
    widthLu: 10,
    depthLu: 4,
    spacingServiceLu: 3,
    spacingAisleLu: 7,
    capacitySeated: 0,
    capacityStaff: 2,
    neutralNote: "",
    visualVariant: "rect",
    iconKey: "bar",
    description: "Portable bar with guest-facing service side.",
    tags: ["bar", "beverage", "fnb", "service"],
  },
  {
    id: "fnb-coffee-station",
    label: "Coffee station",
    category: "fnb",
    shapeType: "planner-buffet",
    domainKind: "buffet",
    widthLu: 8,
    depthLu: 3,
    spacingServiceLu: 2,
    spacingAisleLu: 5,
    capacitySeated: 0,
    capacityStaff: 1,
    neutralNote: "",
    visualVariant: "rect",
    iconKey: "coffee",
    description: "Coffee / beverage station for breaks or hospitality.",
    tags: ["coffee", "beverage", "break", "station"],
  },
  {
    id: "lounge-chair",
    label: "Lounge chair",
    category: "lounge",
    shapeType: "planner-operational-fixture",
    domainKind: "chair_block",
    widthLu: 3.6,
    depthLu: 3.6,
    spacingServiceLu: 1.5,
    spacingAisleLu: 3,
    capacitySeated: 1,
    capacityStaff: 0,
    neutralNote: "",
    visualVariant: "chair",
    iconKey: "armchair",
    description: "Soft lounge chair for hospitality groupings.",
    tags: ["lounge", "chair", "soft seating"],
  },
  {
    id: "booth-10x10",
    label: "10×10 booth",
    category: "booths",
    shapeType: "planner-operational-fixture",
    domainKind: "registration_desk",
    widthLu: 12.2,
    depthLu: 12.2,
    spacingServiceLu: 2,
    spacingAisleLu: 6,
    capacitySeated: 0,
    capacityStaff: 2,
    neutralNote: "Exhibit footprint",
    visualVariant: "rect",
    iconKey: "booth",
    description: "Standard 10 by 10 exhibit or sponsor booth.",
    tags: ["booth", "exhibit", "sponsor", "10x10"],
  },
  {
    id: "decor-plant-cluster",
    label: "Plant cluster",
    category: "decor",
    shapeType: "planner-operational-fixture",
    domainKind: "aisle_zone",
    widthLu: 4,
    depthLu: 4,
    spacingServiceLu: 1,
    spacingAisleLu: 3,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Decor placement",
    visualVariant: "round",
    iconKey: "sparkles",
    description: "Decorative plant/scenic cluster with low-risk clearance metadata.",
    tags: ["decor", "plant", "scenic"],
  },
  {
    id: "service-corridor",
    label: "Service corridor",
    category: "service",
    shapeType: "planner-aisle-zone",
    domainKind: "aisle_zone",
    widthLu: 8,
    depthLu: 40,
    spacingServiceLu: 0,
    spacingAisleLu: 0,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Back-of-house movement corridor",
    visualVariant: "zone",
    iconKey: "route",
    description: "Staff/service movement corridor.",
    tags: ["service", "corridor", "back of house", "access"],
  },
  {
    id: "service-storage-zone",
    label: "Storage zone",
    category: "service",
    shapeType: "planner-operational-fixture",
    domainKind: "aisle_zone",
    widthLu: 16,
    depthLu: 12,
    spacingServiceLu: 2,
    spacingAisleLu: 4,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Operational storage",
    visualVariant: "zone",
    iconKey: "box",
    description: "Temporary storage / show materials area.",
    tags: ["service", "storage", "back of house"],
  },
  {
    id: "service-staff-access-lane",
    label: "Staff access lane",
    category: "service",
    shapeType: "planner-aisle-zone",
    domainKind: "aisle_zone",
    widthLu: 6,
    depthLu: 36,
    spacingServiceLu: 0,
    spacingAisleLu: 0,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Staff-only circulation",
    visualVariant: "zone",
    iconKey: "route",
    description: "Dedicated staff access lane.",
    tags: ["service", "staff", "access", "lane"],
  },
  {
    id: "safety-egress-path",
    label: "Emergency egress path",
    category: "safety",
    shapeType: "planner-aisle-zone",
    domainKind: "aisle_zone",
    widthLu: 8,
    depthLu: 44,
    spacingServiceLu: 0,
    spacingAisleLu: 0,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Emergency egress clearance",
    visualVariant: "zone",
    iconKey: "shield",
    description: "Emergency egress path cue. Deterministic validation comes later.",
    tags: ["safety", "egress", "emergency", "path"],
  },
  {
    id: "safety-ada-clearance",
    label: "ADA clearance zone",
    category: "safety",
    shapeType: "planner-aisle-zone",
    domainKind: "aisle_zone",
    widthLu: 12,
    depthLu: 12,
    spacingServiceLu: 0,
    spacingAisleLu: 0,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Accessibility clearance",
    visualVariant: "zone",
    iconKey: "accessibility",
    description: "ADA/accessibility clearance zone cue.",
    tags: ["ada", "accessibility", "safety", "clearance"],
  },
  {
    id: "wall-pipe-drape",
    label: "Pipe & drape",
    category: "walls",
    shapeType: "planner-operational-fixture",
    domainKind: "aisle_zone",
    widthLu: 24,
    depthLu: 1,
    spacingServiceLu: 0.5,
    spacingAisleLu: 2,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Temporary divider",
    visualVariant: "wall",
    iconKey: "wall",
    description: "Temporary pipe-and-drape divider run.",
    tags: ["wall", "divider", "pipe", "drape"],
  },
  {
    id: "door-entry",
    label: "Door / entry",
    category: "walls",
    shapeType: "planner-operational-fixture",
    domainKind: "aisle_zone",
    widthLu: 6,
    depthLu: 1.2,
    spacingServiceLu: 0,
    spacingAisleLu: 0,
    capacitySeated: 0,
    capacityStaff: 0,
    neutralNote: "Manual room entry marker",
    visualVariant: "door",
    iconKey: "door",
    description: "Manual entrance or doorway marker with editable width and orientation.",
    tags: ["door", "entry", "entrance", "room feature", "opening"],
  },
] as const satisfies readonly RoomSetComponentBaseDefinition[];

export type RoomSetComponentId = (typeof ROOM_SET_COMPONENT_BASES)[number]["id"];

const categorySmartDefaults: Record<RoomSetComponentCategoryId, RoomSetSmartMetadata> = {
  tables: {
    clearanceRequirements: ["Keep guest chair pull zones clear on all sides.", "Maintain service aisle access to at least one side."],
    capacityLogic: "Capacity is based on seated place settings for dining or standing hospitality use.",
    staffingImpact: "No dedicated staff unless used for service or reset operations.",
    setupComplexity: "low",
    setupEffort: "Place, linen, dress, and align to seating plan.",
    strikeEffort: "Clear tabletop, collapse linen, and remove with banquet team.",
    operationalDependencies: ["Final seating count", "Linen/tabletop order"],
    serviceAccessRequirements: ["Banquet service path to table cluster"],
    adaEgressImplications: ["Avoid narrowing primary circulation around seated guests."],
    avSightlineImplications: ["Watch stage/screen sightlines when tables are near the front third."],
    fnbQueueServiceImplications: ["Dining tables increase server circulation demand."],
    operationalWarnings: ["Dense table grids can pinch guest/service aisles."],
  },
  seating: {
    clearanceRequirements: ["Maintain row pitch and aisle access.", "Keep cross-aisles open for guest entry and exit."],
    capacityLogic: "Capacity is counted from modeled seats in each row/block.",
    staffingImpact: "Ushering need increases with dense row seating.",
    setupComplexity: "medium",
    setupEffort: "Snap rows, align sightlines, tape aisles, and label reserved blocks if needed.",
    strikeEffort: "Stack/reset rows and clear aisle markings.",
    operationalDependencies: ["Final headcount", "Room turn schedule"],
    serviceAccessRequirements: ["Usher and accessibility routes to row ends"],
    adaEgressImplications: ["Reserve companion/ADA areas and keep aisle transitions clear."],
    avSightlineImplications: ["Rows should face stage/screen and avoid FOH obstructions."],
    fnbQueueServiceImplications: ["Avoid placing F&B queues behind tight seated rows."],
    operationalWarnings: ["Rows without visible aisle strategy can create egress pressure."],
  },
  stages: {
    clearanceRequirements: ["Protect downstage edge and backstage/service sides.", "Keep presenter access path open."],
    capacityLogic: "Neutral capacity object; may support presenters, furniture, or scenic.",
    staffingImpact: "Setup usually requires production or staging crew.",
    setupComplexity: "high",
    setupEffort: "Build deck/riser, dress fascia, confirm power/audio/safety access.",
    strikeEffort: "Requires coordinated production strike and freight path.",
    operationalDependencies: ["Run of show", "Power drops", "AV/scenic vendor schedule"],
    serviceAccessRequirements: ["Backstage or side-stage crew access"],
    adaEgressImplications: ["Do not block exit paths; consider ramp/accessibility needs."],
    avSightlineImplications: ["Primary sightline anchor for screens, FOH, cameras, and seating orientation."],
    fnbQueueServiceImplications: ["Keep F&B service away from presenter access and camera paths."],
    operationalWarnings: ["Stage depth and front clearance can consume room capacity quickly."],
  },
  av: {
    clearanceRequirements: ["Keep cable paths and operator clearance protected.", "Avoid guest circulation through technical positions."],
    capacityLogic: "May add operator/staff positions rather than guest capacity.",
    staffingImpact: "Adds AV operator or technician coverage depending on use.",
    setupComplexity: "high",
    setupEffort: "Place gear, run cable, test power/signal, and confirm sightlines.",
    strikeEffort: "Cable pull, gear pack, and vendor pickup coordination.",
    operationalDependencies: ["Power/internet", "Stage/screen position", "AV vendor schedule"],
    serviceAccessRequirements: ["Protected cable/service route to stage or control"],
    adaEgressImplications: ["Cable paths must not cross accessible/egress routes without protection."],
    avSightlineImplications: ["Can obstruct or define screen/stage sightlines; FOH needs line of sight."],
    fnbQueueServiceImplications: ["Keep liquids/service stations away from AV control and cabling."],
    operationalWarnings: ["Unprotected cable/service paths are an operational risk."],
  },
  registration: {
    clearanceRequirements: ["Protect guest-side queueing and staff-side working space."],
    capacityLogic: "Throughput depends on desk/kiosk count and staffing.",
    staffingImpact: "Staffing scales with desk count, badge printing, and guest arrival curve.",
    setupComplexity: "medium",
    setupEffort: "Place desks/kiosks, power printers, set signage, and route queues.",
    strikeEffort: "Pack devices, signage, and stanchions after arrival peak or event close.",
    operationalDependencies: ["Badge/registration provider", "Power", "Signage", "Arrival schedule"],
    serviceAccessRequirements: ["Staff access behind desks and printer supply area"],
    adaEgressImplications: ["Queue lanes must preserve accessible entry and exit routes."],
    avSightlineImplications: ["Usually neutral, but signage/screens should not block primary wayfinding."],
    fnbQueueServiceImplications: ["Avoid crossing registration queues with coffee/break lines."],
    operationalWarnings: ["Queue lanes can silently consume lobby/foyer capacity."],
  },
  fnb: {
    clearanceRequirements: ["Keep guest queue side and staff/service side distinct.", "Maintain replenishment path."],
    capacityLogic: "Throughput and queue length depend on station count and menu style.",
    staffingImpact: "Adds culinary/service staffing and replenishment coverage.",
    setupComplexity: "medium",
    setupEffort: "Place tables/bars, dress service, run power if needed, and stage supplies.",
    strikeEffort: "Food/beverage clear, rental strike, waste removal, and stewarding.",
    operationalDependencies: ["Catering order", "Power/water if needed", "Service timing", "Waste plan"],
    serviceAccessRequirements: ["Back-of-house replenishment and waste route"],
    adaEgressImplications: ["Queues must not block exits, ADA paths, or room entry."],
    avSightlineImplications: ["Queues and bars can obstruct views if placed near stage/screen axis."],
    fnbQueueServiceImplications: ["Requires queue planning and service-side working clearance."],
    operationalWarnings: ["Popular stations need extra queue depth and staff access."],
  },
  lounge: {
    clearanceRequirements: ["Preserve circulation around soft seating clusters."],
    capacityLogic: "Capacity is soft/estimated from modeled seats and informal standing space.",
    staffingImpact: "Usually low staffing impact unless hosted/sponsored.",
    setupComplexity: "medium",
    setupEffort: "Place furniture, power/decor if needed, and align conversation zones.",
    strikeEffort: "Furniture pickup/reset and decor removal.",
    operationalDependencies: ["Furniture order", "Sponsor/scenic direction"],
    serviceAccessRequirements: ["Access for furniture install and turnover"],
    adaEgressImplications: ["Soft seating must not creep into accessible routes."],
    avSightlineImplications: ["Low profile generally, but avoid blocking camera/stage paths."],
    fnbQueueServiceImplications: ["Works well near hospitality; avoid blocking bar/buffet lines."],
    operationalWarnings: ["Loose lounge layouts can drift into circulation without clear boundaries."],
  },
  booths: {
    clearanceRequirements: ["Keep exhibit face and aisle approach clear."],
    capacityLogic: "Adds sponsor/staff presence, not primary audience capacity.",
    staffingImpact: "May require exhibitor staff and show-floor support.",
    setupComplexity: "medium",
    setupEffort: "Mark booth footprint, deliver table/power, install branding.",
    strikeEffort: "Exhibitor pack-out and freight/service path coordination.",
    operationalDependencies: ["Sponsor specs", "Power/internet", "Freight timing"],
    serviceAccessRequirements: ["Aisle and freight/service access"],
    adaEgressImplications: ["Do not constrict show aisles or accessible routes."],
    avSightlineImplications: ["Tall booth elements can block sightlines or wayfinding."],
    fnbQueueServiceImplications: ["Avoid booth placement that conflicts with F&B queues."],
    operationalWarnings: ["Booth freight and power needs are often underplanned."],
  },
  decor: {
    clearanceRequirements: ["Keep decor outside paths, doors, and service lanes."],
    capacityLogic: "Neutral object; consumes footprint but adds no capacity.",
    staffingImpact: "Decor install/strike support may be needed.",
    setupComplexity: "low",
    setupEffort: "Place and dress scenic/decor elements.",
    strikeEffort: "Remove decor and restore room condition.",
    operationalDependencies: ["Decor/scenic order", "Fire/safety review if applicable"],
    serviceAccessRequirements: ["Install access and safe storage path"],
    adaEgressImplications: ["Decor must not narrow ADA or emergency paths."],
    avSightlineImplications: ["Tall decor may affect camera, projection, or presenter views."],
    fnbQueueServiceImplications: ["Decor near F&B should not reduce queue or replenishment space."],
    operationalWarnings: ["Decor is low-risk only when it stays out of circulation."],
  },
  service: {
    clearanceRequirements: ["Keep full lane width unobstructed for staff and equipment movement."],
    capacityLogic: "Neutral operational zone; protects movement, storage, or access.",
    staffingImpact: "Improves staff efficiency and may reduce congestion risk.",
    setupComplexity: "low",
    setupEffort: "Mark/protect lane or zone and coordinate with operations team.",
    strikeEffort: "Clear tape/signage and remove stored materials.",
    operationalDependencies: ["Operations plan", "Vendor access schedule"],
    serviceAccessRequirements: ["Primary service route; keep continuous where possible"],
    adaEgressImplications: ["Service paths should not compete with ADA/egress paths."],
    avSightlineImplications: ["Service lanes near FOH/camera positions need coordination."],
    fnbQueueServiceImplications: ["Critical for replenishment, bussing, and waste movement."],
    operationalWarnings: ["If this lane is blocked, operational recovery gets much harder."],
  },
  safety: {
    clearanceRequirements: ["Keep zone/path fully clear and legible."],
    capacityLogic: "Safety/egress object; does not add capacity.",
    staffingImpact: "May require marshal/usher monitoring during peaks.",
    setupComplexity: "medium",
    setupEffort: "Mark path/clearance and align with venue/fire-life-safety guidance.",
    strikeEffort: "Remove temporary markings/signage after event.",
    operationalDependencies: ["Venue egress plan", "Fire marshal/venue review if applicable"],
    serviceAccessRequirements: ["Must remain clear of storage and service staging"],
    adaEgressImplications: ["Primary ADA/egress implication; do not obstruct."],
    avSightlineImplications: ["Generally neutral, but AV cabling must not cross unprotected."],
    fnbQueueServiceImplications: ["F&B queues must never spill into this area."],
    operationalWarnings: ["Informational only for now; validation engine comes later."],
  },
  walls: {
    clearanceRequirements: ["Maintain door, exit, and airwall operation clearances."],
    capacityLogic: "Divider footprint; can shape room capacity and circulation.",
    staffingImpact: "May require venue labor, scenic, or drape vendor support.",
    setupComplexity: "medium",
    setupEffort: "Install divider/drape, confirm stability, and preserve access points.",
    strikeEffort: "Vendor/venue labor strike and equipment removal.",
    operationalDependencies: ["Venue labor", "Drape/scenic vendor", "Fire/safety review if applicable"],
    serviceAccessRequirements: ["Do not cut off service access or emergency routes"],
    adaEgressImplications: ["Divider placement can create inaccessible pinch points."],
    avSightlineImplications: ["Walls/dividers alter acoustics, projection, and camera views."],
    fnbQueueServiceImplications: ["Can hide or constrain F&B/service queues."],
    operationalWarnings: ["Divider placement can change room behavior more than the footprint suggests."],
  },
};

function smartMetadataForComponent(
  component: RoomSetComponentBaseDefinition,
): RoomSetSmartMetadata {
  const base = categorySmartDefaults[component.category];
  const withWarnings = (warnings: readonly string[]): RoomSetSmartMetadata => ({
    ...base,
    operationalWarnings: [...base.operationalWarnings, ...warnings],
  });

  switch (component.id) {
    case "table-cocktail":
    case "table-cocktail-cluster":
      return {
        ...base,
        capacityLogic: component.id === "table-cocktail-cluster"
          ? "One highboy cluster with four stools; rendered as a single canvas object for dense reception performance."
          : "Standing touchpoint; do not count as seated capacity.",
        fnbQueueServiceImplications: ["Useful near receptions, bars, and networking areas without creating a full service queue."],
        operationalWarnings: [...base.operationalWarnings, "Cocktail tables drift easily; preserve aisle rhythm."],
      };
    case "seating-theater-row":
      return withWarnings(["Confirm rows face the intended stage/screen axis."]);
    case "seating-classroom-row":
      return {
        ...base,
        capacityLogic: "Capacity assumes paired classroom seating at training tables.",
        avSightlineImplications: ["Rows need clear screen view and adequate front teaching distance."],
        operationalWarnings: [...base.operationalWarnings, "Classroom rows need more depth than theater seating."],
      };
    case "stage-keynote":
      return withWarnings(["Coordinate stage, screen, FOH, camera, and backstage as one system."]);
    case "stage-riser":
      return {
        ...base,
        setupComplexity: "medium",
        operationalWarnings: [...base.operationalWarnings, "Confirm riser height, stairs, railing, and accessibility needs."],
      };
    case "av-foh-control":
      return withWarnings(["FOH must maintain direct sightline to stage/screens and protected cable paths."]);
    case "av-confidence-monitor":
      return {
        ...base,
        operationalDependencies: [...base.operationalDependencies, "Presenter position"],
        avSightlineImplications: ["Presenter-facing only; avoid audience-facing obstruction."],
      };
    case "registration-queue-lane":
      return withWarnings(["Queue lane should terminate before doors, stairs, and F&B queues."]);
    case "fnb-buffet-line":
      return withWarnings(["Buffet lines often need deeper guest queue space than the table footprint."]);
    case "fnb-portable-bar":
      return withWarnings(["Bar service needs spillover queue space and waste/ice replenishment access."]);
    case "service-corridor":
    case "service-staff-access-lane":
      return withWarnings(["Keep this lane continuous; partial obstruction defeats the operational purpose."]);
    case "safety-egress-path":
    case "safety-ada-clearance":
      return withWarnings(["Future validation will treat this as high-priority clearance metadata."]);
    case "wall-pipe-drape":
      return withWarnings(["Confirm drape does not hide exit signage or block fire equipment."]);
    case "door-entry":
      return {
        ...base,
        capacityLogic: "Manual room-feature marker; does not add seating or staff capacity.",
        serviceAccessRequirements: ["Keep doorway approach clear for guest, staff, ADA, and emergency movement."],
        adaEgressImplications: ["Door markers should remain visibly clear and not be blocked by furniture or queues."],
        operationalWarnings: [...base.operationalWarnings, "Door markers are manual room features and are not auto-placed."],
      };
    default:
      return base;
  }
}

export const ROOM_SET_COMPONENTS: readonly RoomSetComponentDefinition[] =
  ROOM_SET_COMPONENT_BASES.map((component) => ({
    ...component,
    smart: smartMetadataForComponent(component),
  }));

export const ROOM_SET_COMPONENT_BY_ID = new Map<string, RoomSetComponentDefinition>(
  ROOM_SET_COMPONENTS.map((component) => [component.id, component]),
);

export function getRoomSetComponent(id: string): RoomSetComponentDefinition | undefined {
  return ROOM_SET_COMPONENT_BY_ID.get(id);
}

export function searchRoomSetComponents(query: string): RoomSetComponentDefinition[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return [...ROOM_SET_COMPONENTS];
  return ROOM_SET_COMPONENTS.filter((component) => {
    const haystack = [
      component.label,
      component.description,
      component.category,
      ...component.tags,
    ]
      .join(" ")
      .toLowerCase();
    return haystack.includes(normalized);
  });
}

export function groupRoomSetComponentsByCategory(
  components: readonly RoomSetComponentDefinition[],
): Map<RoomSetComponentCategoryId, RoomSetComponentDefinition[]> {
  const grouped = new Map<RoomSetComponentCategoryId, RoomSetComponentDefinition[]>();
  for (const category of ROOM_SET_COMPONENT_CATEGORY_IDS) grouped.set(category, []);
  for (const component of components) grouped.get(component.category)?.push(component);
  return grouped;
}
