type RequestWithUrl = Pick<Request, "url">;

function isWildcardBindHostname(hostname: string) {
  return hostname === "0.0.0.0" || hostname === "[::]" || hostname === "::";
}

/**
 * Resolve the origin a browser should see for redirects generated by the app.
 *
 * Next dev may expose its `0.0.0.0` bind address as `request.url`. That address
 * is valid for listening but must never replace the host that initiated the
 * browser session. Production and preview origins are returned unchanged.
 */
export function getBrowserFacingOrigin(
  request: RequestWithUrl
) {
  const requestUrl = new URL(request.url);
  if (!isWildcardBindHostname(requestUrl.hostname)) {
    return requestUrl.origin;
  }

  const port = requestUrl.port ? `:${requestUrl.port}` : "";
  return `${requestUrl.protocol}//localhost${port}`;
}

export function buildBrowserFacingUrl(
  request: RequestWithUrl,
  path: string
) {
  return new URL(path, getBrowserFacingOrigin(request));
}
