import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHeader } from "@signalthread/ui";
import { ensureProvisionedUserAndContext } from "@/lib/request-user";
import { requirePlatformAdminFromContext, PlatformAdminAuthError } from "@/src/server/auth/platform-admin";
import { getPlatformUserDetail, PlatformAdminServiceError } from "@/src/server/services/platform-admin";
import { PlatformUserRoleEditor } from "../../_components/platform-user-role-editor";
import { eventAccessRoleLabel, platformRoleLabel } from "@/lib/platform-admin-labels";

export default async function PlatformUserDetailPage({ params }: { params: Promise<{ userId: string }> }) {
  let user;
  try { user = await getPlatformUserDetail((await params).userId); } catch (error) { if (error instanceof PlatformAdminServiceError && error.reason === "USER_NOT_FOUND") notFound(); throw error; }
  let operatorId: string | null = null;
  try { operatorId = requirePlatformAdminFromContext(await ensureProvisionedUserAndContext()).id; } catch (error) { if (error instanceof PlatformAdminAuthError) throw error; }
  return <div className="mx-auto max-w-6xl space-y-5"><PageHeader eyebrow="Platform user" title={user.name || user.email} description={user.email} actions={<Link className="rounded-lg border border-slate-300 px-4 py-2 font-semibold text-slate-700" href="/platform/users">Back to users</Link>} /><div className="flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold text-slate-700">{platformRoleLabel(user.role)}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-sm text-slate-600">{user.accountCount} memberships</span><span className="rounded-full bg-slate-100 px-3 py-1 text-sm text-slate-600">{user.totalEventAccessGrants} event access grants</span><span className="rounded-full bg-slate-100 px-3 py-1 text-sm text-slate-600">Joined {user.createdAt.toLocaleDateString()}</span></div><PlatformUserRoleEditor userId={user.id} currentRole={user.role} isCurrentOperator={operatorId === user.id} /><section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold text-slate-950">Memberships and event access</h2><p className="mt-1 text-sm text-slate-500">Accounts this user belongs to and their event access.</p></div>{user.memberships.length === 0 ? <p className="p-5 text-sm text-slate-500">No memberships.</p> : <div className="divide-y divide-slate-100">{user.memberships.map((membership) => <details key={membership.membershipId} className="group p-5" open><summary className="flex cursor-pointer list-none items-center justify-between gap-4"><div><Link onClick={(event) => event.stopPropagation()} className="font-semibold text-[#2d4ba8]" href={`/platform/accounts/${membership.orgId}`}>{membership.accountName}</Link><p className="mt-1 text-sm text-slate-500">Joined {membership.membershipCreatedAt.toLocaleDateString()} · {membership.eventAccessCount} event grants</p></div><span className="text-sm text-slate-500">Details</span></summary>{membership.eventAccess.length ? <div className="mt-4 overflow-x-auto rounded-lg border border-slate-200"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Event</th><th className="px-4 py-3">Event role</th></tr></thead><tbody>{membership.eventAccess.map((grant) => <tr key={grant.eventId} className="border-t border-slate-100"><td className="px-4 py-3 font-medium text-slate-900">{grant.eventName}</td><td className="px-4 py-3 text-slate-600">{eventAccessRoleLabel(grant.eventRole)}</td></tr>)}</tbody></table></div> : <p className="mt-3 text-sm text-slate-500">No event access.</p>}</details>)}</div>}</section></div>;
}
