ALTER TABLE "Event"
  ADD COLUMN IF NOT EXISTS "ttsProvider" TEXT NOT NULL DEFAULT 'google',
  ADD COLUMN IF NOT EXISTS "ttsVoice" TEXT NOT NULL DEFAULT 'en-US-Neural2-F',
  ADD COLUMN IF NOT EXISTS "ttsLocale" TEXT NOT NULL DEFAULT 'en-US';
