"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Preflight = { account: { name: string; slug: string }; blockers: string[]; canDelete: boolean; activeContext: boolean; counts: Record<string, number> };
export function AccountDeleteWorkflow({ orgId }: { orgId: string }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [preflight, setPreflight] = useState<Preflight | null>(null); const [confirmation, setConfirmation] = useState(""); const [message, setMessage] = useState<string | null>(null);
  async function openPreflight() { setOpen(true); setMessage(null); const response = await fetch(`/api/platform/accounts/${orgId}/delete-preflight`, { credentials: "include" }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setMessage(payload.message || "Could not inspect deletion dependencies."); return; } setPreflight(payload.preflight); }
  async function remove() { const response = await fetch(`/api/platform/accounts/${orgId}`, { method: "DELETE", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ confirmation }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) { setMessage(payload.message || "Account could not be deleted."); return; } router.push("/platform/accounts"); router.refresh(); }
  return <section className="rounded-xl border border-rose-200 bg-rose-50 p-4"><h2 className="font-semibold text-rose-950">Delete account</h2><p className="mt-1 text-sm text-rose-800">Deletion is only enabled for a dependency-free account. This never cascades or partially deletes data.</p><button onClick={openPreflight} className="mt-3 rounded-lg border border-rose-300 bg-white px-4 py-2 font-semibold text-rose-700">Review deletion safety</button>{open && <div className="mt-4 rounded-lg border border-rose-200 bg-white p-4">{message && <p className="text-sm text-rose-700">{message}</p>}{!preflight && !message && <p className="text-sm text-slate-500">Checking dependencies…</p>}{preflight && <><p className="text-sm font-medium">{preflight.canDelete ? "This account has no persisted dependencies and can be deleted." : "Deletion is blocked until these dependencies are removed through their own workflows:"}</p>{preflight.blockers.length > 0 && <ul className="mt-2 list-disc pl-5 text-sm text-slate-700">{preflight.blockers.map((blocker) => <li key={blocker}>{blocker}</li>)}</ul>}<label className="mt-4 block text-sm text-slate-700">Type <strong>{preflight.account.name}</strong> or <strong>{preflight.account.slug}</strong> to confirm<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="mt-1 block h-10 w-full rounded border border-slate-300 px-3" /></label><button disabled={!preflight.canDelete || (confirmation !== preflight.account.name && confirmation !== preflight.account.slug)} onClick={remove} className="mt-3 rounded-lg bg-rose-700 px-4 py-2 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">Delete account permanently</button></>}</div>}</section>;
}
