import { NextRequest, NextResponse } from "next/server";
import { requireEventRouteAccess } from "../../../../_lib/event-route-auth";
import { createSessionOperationalRecord, listSessionOperationalRecords, removeSessionOperationalRecord, SessionOperationalRecordError, updateSessionOperationalRecord } from "@/lib/session-operational-records";
export const runtime = "nodejs";
function failure(error: unknown) { if (error instanceof SessionOperationalRecordError) return NextResponse.json({ error: error.message }, { status: error.status }); console.error("Session operations route failed", error); return NextResponse.json({ error: "Internal server error" }, { status: 500 }); }
export async function GET(request: NextRequest, { params }: { params: Promise<{ eventId: string; sessionId: string }> }) { const { eventId, sessionId } = await params; const auth = await requireEventRouteAccess(request, eventId, "read"); if ("response" in auth) return auth.response; try { return NextResponse.json(await listSessionOperationalRecords(eventId, sessionId, request.nextUrl.searchParams.get("module"))); } catch (error) { return failure(error); } }
export async function POST(request: NextRequest, { params }: { params: Promise<{ eventId: string; sessionId: string }> }) { const { eventId, sessionId } = await params; const auth = await requireEventRouteAccess(request, eventId, "write"); if ("response" in auth) return auth.response; try { const body = await request.json(); return NextResponse.json(await createSessionOperationalRecord(eventId, sessionId, body.module, body), { status: 201 }); } catch (error) { return failure(error); } }
export async function PATCH(request: NextRequest, { params }: { params: Promise<{ eventId: string; sessionId: string }> }) { const { eventId, sessionId } = await params; const auth = await requireEventRouteAccess(request, eventId, "write"); if ("response" in auth) return auth.response; try { const body = await request.json(); return NextResponse.json(await updateSessionOperationalRecord(eventId, sessionId, String(body.id ?? ""), body)); } catch (error) { return failure(error); } }
export async function DELETE(request: NextRequest, { params }: { params: Promise<{ eventId: string; sessionId: string }> }) { const { eventId, sessionId } = await params; const auth = await requireEventRouteAccess(request, eventId, "write"); if ("response" in auth) return auth.response; try { await removeSessionOperationalRecord(eventId, sessionId, String(request.nextUrl.searchParams.get("id") ?? "")); return NextResponse.json({ ok: true }); } catch (error) { return failure(error); } }
